version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: SensorManagement.API/Dockerfile
    container_name: sensor-api
    ports:
      - "5000:5000"
      - "5001:5001"
    depends_on:
      - postgres-db
      - redis
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Host=postgres-db;Port=5432;Database=SensorDB;Username=admin;Password=admin"
      Redis__Configuration: "redis:6379"

  postgres-db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: SensorDB
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  postgres-data:
