version: '3'

services:
  sensor-api:
    build:
      context: .
      dockerfile: SensorManagement.API/Dockerfile
    container_name: sensor-api
    ports:
      - "5000:5000"
      - "5001:5001"

  postgres-db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: SensorDB
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  postgres-data:
